"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.$validation = exports.$type = exports.$taskEither = exports.$struct = exports.$string = exports.$storage = exports.$readonlyTuple = exports.$readonlyRecord = exports.$readonlyArray = exports.$readerTaskEither = exports.$readerTask = exports.$readerEither = exports.$reader = exports.$random = exports.$option = exports.$number = exports.$mock = exports.$matrix = exports.$magma = exports.$log = exports.$http = exports.$generatorL = exports.$error = exports.$eq = exports.$date = exports.$console = exports.$cache = exports.$buffer = exports.$binary = exports.$aggregate = void 0;
const $aggregate = __importStar(require("./Aggregate"));
exports.$aggregate = $aggregate;
const $binary = __importStar(require("./Binary"));
exports.$binary = $binary;
const $buffer = __importStar(require("./Buffer"));
exports.$buffer = $buffer;
const $cache = __importStar(require("./Cache"));
exports.$cache = $cache;
const $console = __importStar(require("./Console"));
exports.$console = $console;
const $date = __importStar(require("./Date"));
exports.$date = $date;
const $eq = __importStar(require("./Eq"));
exports.$eq = $eq;
const $error = __importStar(require("./Error"));
exports.$error = $error;
const $generatorL = __importStar(require("./GeneratorL"));
exports.$generatorL = $generatorL;
const $http = __importStar(require("./Http"));
exports.$http = $http;
const $log = __importStar(require("./Log"));
exports.$log = $log;
const $magma = __importStar(require("./Magma"));
exports.$magma = $magma;
const $matrix = __importStar(require("./Matrix"));
exports.$matrix = $matrix;
const $mock = __importStar(require("./Mock"));
exports.$mock = $mock;
const $number = __importStar(require("./number"));
exports.$number = $number;
const $option = __importStar(require("./Option"));
exports.$option = $option;
const $random = __importStar(require("./Random"));
exports.$random = $random;
const $reader = __importStar(require("./Reader"));
exports.$reader = $reader;
const $readerEither = __importStar(require("./ReaderEither"));
exports.$readerEither = $readerEither;
const $readerTask = __importStar(require("./ReaderTask"));
exports.$readerTask = $readerTask;
const $readerTaskEither = __importStar(require("./ReaderTaskEither"));
exports.$readerTaskEither = $readerTaskEither;
const $readonlyArray = __importStar(require("./ReadonlyArray"));
exports.$readonlyArray = $readonlyArray;
const $readonlyRecord = __importStar(require("./ReadonlyRecord"));
exports.$readonlyRecord = $readonlyRecord;
const $readonlyTuple = __importStar(require("./ReadonlyTuple"));
exports.$readonlyTuple = $readonlyTuple;
const $storage = __importStar(require("./Storage"));
exports.$storage = $storage;
const $string = __importStar(require("./string"));
exports.$string = $string;
const $struct = __importStar(require("./struct"));
exports.$struct = $struct;
const $taskEither = __importStar(require("./TaskEither"));
exports.$taskEither = $taskEither;
const $type = __importStar(require("./Type"));
exports.$type = $type;
const $validation = __importStar(require("./Validation"));
exports.$validation = $validation;
