"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.$validation = exports.$type = exports.$struct = exports.$string = exports.$readonlyTuple = exports.$readonlyRecord = exports.$readonlyArray = exports.$readerTaskEither = exports.$readerTask = exports.$readerEither = exports.$reader = exports.$option = exports.$optics = exports.$mock = exports.$matrix = exports.$magma = exports.$generatorL = exports.$eq = exports.$date = exports.$binary = exports.$aggregate = void 0;
var $aggregate = __importStar(require("./Aggregate"));
exports.$aggregate = $aggregate;
var $binary = __importStar(require("./Binary"));
exports.$binary = $binary;
var $date = __importStar(require("./Date"));
exports.$date = $date;
var $eq = __importStar(require("./Eq"));
exports.$eq = $eq;
var $generatorL = __importStar(require("./GeneratorL"));
exports.$generatorL = $generatorL;
var $magma = __importStar(require("./Magma"));
exports.$magma = $magma;
var $matrix = __importStar(require("./Matrix"));
exports.$matrix = $matrix;
var $mock = __importStar(require("./Mock"));
exports.$mock = $mock;
var $optics = __importStar(require("./Optics"));
exports.$optics = $optics;
var $option = __importStar(require("./Option"));
exports.$option = $option;
var $reader = __importStar(require("./Reader"));
exports.$reader = $reader;
var $readerEither = __importStar(require("./ReaderEither"));
exports.$readerEither = $readerEither;
var $readerTask = __importStar(require("./ReaderTask"));
exports.$readerTask = $readerTask;
var $readerTaskEither = __importStar(require("./ReaderTaskEither"));
exports.$readerTaskEither = $readerTaskEither;
var $readonlyArray = __importStar(require("./ReadonlyArray"));
exports.$readonlyArray = $readonlyArray;
var $readonlyRecord = __importStar(require("./ReadonlyRecord"));
exports.$readonlyRecord = $readonlyRecord;
var $readonlyTuple = __importStar(require("./ReadonlyTuple"));
exports.$readonlyTuple = $readonlyTuple;
var $string = __importStar(require("./string"));
exports.$string = $string;
var $struct = __importStar(require("./struct"));
exports.$struct = $struct;
var $type = __importStar(require("./Type"));
exports.$type = $type;
var $validation = __importStar(require("./Validation"));
exports.$validation = $validation;
